name: Publish
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
jobs:
  gh-pages:
    if: ${{!startsWith(github.event.head_commit.message, '[RELEASE]') || !startsWith(github.event.head_commit.message, '[GIF]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: git config --global user.name 'Nils Baumgartner'
      - run: git config --global user.email 'nilsbaumgartner1994@gmail.com'
      #https://www.npmjs.com/package/gh-pages
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          CI=false npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
